In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle

In [3]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
## Preprocessing the data
### Dropping unnecessary columns

cleaned_data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)
cleaned_data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
label_encoder_gender = LabelEncoder()
cleaned_data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
cleaned_data.head(10)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
5,645,Spain,1,44,8,113755.78,2,1,0,149756.71,1
6,822,France,1,50,7,0.00,2,1,1,10062.80,0
7,376,Germany,0,29,4,115046.74,4,1,0,119346.88,1
8,501,France,1,44,4,142051.07,2,0,1,74940.50,0
9,684,France,1,27,2,134603.88,1,1,1,71725.73,0

In [7]:
# one hot encoding for geography column
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geography = OneHotEncoder()

geography_encoded = onehot_encoder_geography.fit_transform(cleaned_data[['Geography']])
geography_encoded

geo_encoded_df = pd.DataFrame(geography_encoded.toarray(),columns=onehot_encoder_geography.get_feature_names_out(['Geography']))
geo_encoded_df.head(10)

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0
5               0.0                0.0              1.0
6               1.0                0.0              0.0
7               0.0                1.0              0.0
8               1.0                0.0              0.0
9               1.0                0.0              0.0

In [9]:
cleaned_data = pd.concat([cleaned_data.drop('Geography',axis=1),geo_encoded_df],axis=1)
cleaned_data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [11]:
x = cleaned_data.drop('EstimatedSalary',axis=1)
y = cleaned_data['EstimatedSalary']

In [12]:
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.2,random_state=42)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
## Save the encoders and scaler
with open('label_encoder_gender_regression.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo_regression.pkl','wb') as file:
    pickle.dump(onehot_encoder_geography,file)

with open('scaler_regression.pkl','wb') as file:
    pickle.dump(scaler,file)

##### ANN Regression statement

In [14]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [15]:
## Build our ANN Model
regression_model = Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1)    #output layer for regression
])

c:\Study\Gen AI Prep\ANN Classification\.venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [21]:
## Compile the model
regression_model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])
regression_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
## Set up the tensorboard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
log_dir = "regression_logs/fit/"
tensorflow_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [23]:
# Set up early stopping
early_stopping_callback = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [24]:
history = regression_model.fit(
    X_train,Y_train,
    validation_data = (X_test,Y_test),
    epochs=100,
    callbacks=[early_stopping_callback,tensorflow_callback]
)

Epoch 1/100

250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - loss: 100377.2266 - mae: 100377.2266 - val_loss: 98518.1328 - val_mae: 98518.1328
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 99665.0469 - mae: 99665.0469 - val_loss: 97094.0000 - val_mae: 97094.0000
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 97202.4531 - mae: 97202.4531 - val_loss: 93480.6250 - val_mae: 93480.6250
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 92363.4219 - mae: 92363.4219 - val_loss: 87435.3984 - val_mae: 87435.3984
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 85241.7422 - mae: 85241.7422 - val_loss: 79509.5703 - val_mae: 79509.5703
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 76686.9062 - mae: 76686.9062 - val_loss: 71018.0312 - val_mae: 71018.0312
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 68125.8281 - mae: 68125.8281 - val_loss: 63185.8906 - val_mae: 63185.8906
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 60824.8789 - mae: 60824.8789 - val_loss: 57339.2930 - val_mae: 57339.2930
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 55717.1875 - mae: 55717.1875 - val_loss: 53615.7227 - val_mae: 53615.7227
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 52767.7930 - mae: 52767.7930 - val_loss: 51770.6445 - val_mae: 51770.6445
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 51331.4609 - mae: 51331.4609 - val_loss: 51107.0977 - val_mae: 51107.0977
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50757.6836 - mae: 50757.6836 - val_loss: 50917.6445 - val_mae: 50917.6445
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50522.4102 - mae: 50522.4102 - val_loss: 50829.8086 - val_mae: 50829.8086
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50407.4297 - mae: 50407.4297 - val_loss: 50781.9414 - val_mae: 50781.9414
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50327.3438 - mae: 50327.3438 - val_loss: 50738.9688 - val_mae: 50738.9688
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50262.5898 - mae: 50262.5898 - val_loss: 50691.3203 - val_mae: 50691.3203
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50207.8672 - mae: 50207.8672 - val_loss: 50651.8008 - val_mae: 50651.8008
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50159.4453 - mae: 50159.4453 - val_loss: 50620.8555 - val_mae: 50620.8555
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50113.7266 - mae: 50113.7266 - val_loss: 50596.0859 - val_mae: 50596.0859
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50074.4961 - mae: 50074.4961 - val_loss: 50572.4219 - val_mae: 50572.4219
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50038.0156 - mae: 50038.0156 - val_loss: 50543.1445 - val_mae: 50543.1445
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50004.6797 - mae: 50004.6797 - val_loss: 50522.4414 - val_mae: 50522.4414
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49971.7148 - mae: 49971.7148 - val_loss: 50500.9727 - val_mae: 50500.9727
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49943.5352 - mae: 49943.5352 - val_loss: 50485.1875 - val_mae: 50485.1875
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49918.4922 - mae: 49918.4922 - val_loss: 50463.0430 - val_mae: 50463.0430
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49893.1445 - mae: 49893.1445 - val_loss: 50453.4258 - val_mae: 50453.4258
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49869.3516 - mae: 49869.3516 - val_loss: 50441.4219 - val_mae: 50441.4219
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49849.3242 - mae: 49849.3242 - val_loss: 50429.3789 - val_mae: 50429.3789
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49827.9492 - mae: 49827.9492 - val_loss: 50411.2852 - val_mae: 50411.2852
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49810.0273 - mae: 49810.0273 - val_loss: 50407.1250 - val_mae: 50407.1250
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49794.6953 - mae: 49794.6953 - val_loss: 50388.6914 - val_mae: 50388.6914
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49773.7852 - mae: 49773.7852 - val_loss: 50377.1797 - val_mae: 50377.1797
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49760.1094 - mae: 49760.1094 - val_loss: 50374.8125 - val_mae: 50374.8125
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49742.2422 - mae: 49742.2422 - val_loss: 50370.8203 - val_mae: 50370.8203
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49728.5000 - mae: 49728.5000 - val_loss: 50364.0312 - val_mae: 50364.0312
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49715.7070 - mae: 49715.7070 - val_loss: 50359.4727 - val_mae: 50359.4727
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49700.0742 - mae: 49700.0742 - val_loss: 50353.3750 - val_mae: 50353.3750
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49688.0312 - mae: 49688.0312 - val_loss: 50352.9141 - val_mae: 50352.9141
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49674.9688 - mae: 49674.9688 - val_loss: 50350.0195 - val_mae: 50350.0195
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49667.8711 - mae: 49667.8711 - val_loss: 50341.4375 - val_mae: 50341.4375
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49652.7656 - mae: 49652.7656 - val_loss: 50332.9258 - val_mae: 50332.9258
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49641.3711 - mae: 49641.3711 - val_loss: 50337.1875 - val_mae: 50337.1875
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49633.2266 - mae: 49633.2266 - val_loss: 50333.0703 - val_mae: 50333.0703
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49626.8398 - mae: 49626.8398 - val_loss: 50326.8164 - val_mae: 50326.8164
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49616.3086 - mae: 49616.3086 - val_loss: 50335.8867 - val_mae: 50335.8867
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49606.8281 - mae: 49606.8281 - val_loss: 50321.0391 - val_mae: 50321.0391
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49597.7227 - mae: 49597.7227 - val_loss: 50318.1641 - val_mae: 50318.1641
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49591.1992 - mae: 49591.1992 - val_loss: 50319.5664 - val_mae: 50319.5664
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49584.1445 - mae: 49584.1445 - val_loss: 50307.0703 - val_mae: 50307.0703
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49577.8516 - mae: 49577.8516 - val_loss: 50303.1914 - val_mae: 50303.1914
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 49569.0273 - mae: 49569.0273 - val_loss: 50310.1680 - val_mae: 50310.1680
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49562.4141 - mae: 49562.4141 - val_loss: 50309.6719 - val_mae: 50309.6719
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49556.2109 - mae: 49556.2109 - val_loss: 50304.1094 - val_mae: 50304.1094
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49546.6328 - mae: 49546.6328 - val_loss: 50301.2109 - val_mae: 50301.2109
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49540.3320 - mae: 49540.3320 - val_loss: 50297.8516 - val_mae: 50297.8516
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49535.6719 - mae: 49535.6719 - val_loss: 50293.6836 - val_mae: 50293.6836
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49530.1172 - mae: 49530.1172 - val_loss: 50316.0938 - val_mae: 50316.0938
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49526.3281 - mae: 49526.3281 - val_loss: 50311.3164 - val_mae: 50311.3164
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49516.8047 - mae: 49516.8047 - val_loss: 50306.6523 - val_mae: 50306.6523
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49509.5039 - mae: 49509.5039 - val_loss: 50300.1211 - val_mae: 50300.1211
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49505.2461 - mae: 49505.2461 - val_loss: 50291.6680 - val_mae: 50291.6680
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49500.7461 - mae: 49500.7461 - val_loss: 50304.7070 - val_mae: 50304.7070
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49492.2422 - mae: 49492.2422 - val_loss: 50297.5078 - val_mae: 50297.5078
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49487.5391 - mae: 49487.5391 - val_loss: 50289.7031 - val_mae: 50289.7031
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49484.1172 - mae: 49484.1172 - val_loss: 50285.2383 - val_mae: 50285.2383
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49478.5469 - mae: 49478.5469 - val_loss: 50295.2188 - val_mae: 50295.2188
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49471.7969 - mae: 49471.7969 - val_loss: 50302.0859 - val_mae: 50302.0859
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49465.2773 - mae: 49465.2773 - val_loss: 50300.3828 - val_mae: 50300.3828
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49466.5859 - mae: 49466.5859 - val_loss: 50294.1484 - val_mae: 50294.1484
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49459.4883 - mae: 49459.4883 - val_loss: 50294.1641 - val_mae: 50294.1641
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49450.5234 - mae: 49450.5234 - val_loss: 50299.5078 - val_mae: 50299.5078
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49447.0117 - mae: 49447.0117 - val_loss: 50295.9258 - val_mae: 50295.9258
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49442.6719 - mae: 49442.6719 - val_loss: 50297.3711 - val_mae: 50297.3711
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 49439.4375 - mae: 49439.4375 - val_loss: 50294.1523 - val_mae: 50294.1523
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49433.1211 - mae: 49433.1211 - val_loss: 50299.8398 - val_mae: 50299.8398

In [26]:
%load_ext tensorboard

In [30]:
%tensorboard --logdir regression_logs/fit

Reusing TensorBoard on port 6006 (pid 12364), started 0:06:04 ago. (Use '!kill 12364' to kill it.)

In [32]:
## Evaluate the model
test_loss,test_mae = regression_model.evaluate(X_test,Y_test)
print(test_loss)
print(test_mae)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 50285.2383 - mae: 50285.2383
50285.23828125
50285.23828125

In [33]:
regression_model.save('salary_regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.